[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.zip", "php82Extensions.pdo", "php82Extensions.pdo_mysql"] 